mahmoud/zerover

- projects.yaml
**Project name**: mpd
**Project link**: https://www.musicpd.org/
---
> Add project: mpd

- projects.yaml
I hope I did this right - this is just adding the entry mentioned in https://github.com/mahmoud/zerover/issues/25
> Add project: wkhtmltopdf

- projects.yaml
Addresses #28
**Project name**:
**Project link**:
---
> Add project: Pywinauto

- projects.yaml
**Project name**: C/C++ for Visual Studio Code
**Project link**: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
Created by Microsoft and with almost 8 million installs, this is the standard extension you want if working with C or C++ in VS Code.
---
> Add project: C/C++ for Visual Studio Code

- projects.yaml
> Add project: Windows Terminal

- projects.yaml
**Project name**: PHPStan
**Project link**: https://github.com/phpstan/phpstan
Currently 8,200 stars on GitHub, more than 9,7 million downloads on Packagist. Currently on version 0.12.10.
Introductory article to PHPStan when I first released it: https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3
---
> Add project: PHPStan

- projects.yaml
Flow is a project that makes it possible to use types in JavaScript.
**Project name**: Flow
**Project link**:
* https://github.com/facebook/flow
* https://flow.org
---
> Add project: Flow

- projects.yaml
Closes #48
**Project name**:
**Project link**:
---
> Add project: GoReleaser

- projects.yaml
**Project name**: JaCoCo
**Project link**:  https://github.com/jacoco/jacoco
---
> Add project: JaCoCo

- projects.yaml
Closes #50
**Project name**: iodine
**Project link**: https://github.com/yarrick/iodine
---
> Add iodine

- projects.yaml
**Project name**: foreman
**Project link**: https://github.com/ddollar/foreman
---
> Add foreman

- projects.yaml
**Project name**: Factorio
**Project link**: https://factorio.com/blog/post/fff-360
> Factorio 1.0!

- projects.yaml
**Project name**: Cosmos-sdk & Tendermint 
**Project link**: https://github.com/cosmos/cosmos-sdk/ & https://github.com/tendermint/tendermint/ 
---
> Add projects: Cosmos-sdk & Tendermint

- projects.yaml
**Project name**: yup
**Project link**: https://github.com/jquense/yup
---
> Add project: Yup

- projects.yaml
Refs #88.
**Project name**: Datasette
**Project link**: https://datasette.io/
---
> Add Datasette, refs #88

- projects.yaml
**Project name**: LocalStack
**Project link**: https://github.com/localstack/localstack
Criteria for [ZeroVer](https://zerover.org)'s patent-pending zero-based versioning
scheme:
Better be quick - we may be publishing a 1.0 release soon! (or never ...)
> Add project: LocalStack

- projects.yaml
**Project name**: XMonad
**Project link**: https://xmonad.org/, https://github.com/xmonad
n/a
> Add project: XMonad

- projects.yaml
**Project name**: Video Speed Controller
**Project link**: https://github.com/igrigorik/videospeed
---
> Add project: Video Speed Controller

- projects.yaml
**Project name**: Pyre
**Project link**: https://github.com/facebook/pyre-check
---
> Add project: Pyre

- projects.yaml
**Project name**: Flipper
**Project link**:https://github.com/flippercloud/flipper
There are a lot of blog posts about adding flipper to your projects
- https://blog.appsignal.com/2022/06/08/add-feature-flags-in-ruby-on-rails-with-flipper.html
- https://www.honeybadger.io/blog/flipper-feature-flags-rails/
- (2015) https://www.johnnunemaker.com/flipper/
---
> Add flipper

- projects.yaml
**Project name**: CorsixTH
**Project link**: https://github.com/CorsixTH/CorsixTH
---
> Add project: CorsixTH

- projects.yaml
**Project name**: Cartopy
**Project link**: https://github.com/SciTools/cartopy
---
> Add project: Cartopy

- projects.yaml
**Project name**: fzf
**Project link**: https://github.com/junegunn/fzf
fzf is probably the most famous terminal fuzzy finder
---
> Add project: fzf

- projects.yaml
**Project name**: Create
**Project link**: https://github.com/Creators-of-Create/Create
Major mod for Minecraft, the [best-selling video game ever](https://en.wikipedia.org/wiki/List_of_best-selling_video_games)
> Add project: Create

- projects.yaml
**Project name**: Hy
**Project link**: https://github.com/hylang/hy
---
I'm the maintainer, so this PR is a confession of sin. Version 1.0 is still supposed to come out Real Soon Now™.
> Add project: Hy

- projects.yaml
**Project name**: Zola
**Project link**: https://www.getzola.org/
It is a rival to Hugo but unlike Hugo is still version 0
---
> Add project: Zola

- projects.yaml
**Project name**: Tectonic
**Project link**: https://tectonic-typesetting.github.io/
A TeX distributon that has been version 0 since 2016
---
> Add project: Tectonic

- projects.yaml
**Project name**: cargo-audit
**Project link**: https://github.com/rustsec/rustsec/blob/main/cargo-audit/README.md
The tool that everyone in the Rust community uses to audit their project dependencies is still version 0 all these years later
---
> Add project: cargo-audit

- projects.yaml
**Project name**: restic
**Project link**: https://restic.net/
---
> Add project: restic

- projects.yaml
**Project name**: PyVista
**Project link**: https://docs.pyvista.org/
**GitHub link**: https://github.com/pyvista/pyvista
Popular wrapper for the leading library in scientific visualization.
> Add Project: PyVista

- projects.yaml
Closes #98
**Project name**: Metabase
**Project link**: https://github.com/metabase/metabase
---
> Add project: Metabase

- projects.yaml
Closes #141
**Project name**: OpenBLAS
**Project link**: https://github.com/OpenMathLib/OpenBLAS
See #141
---
> Add project: OpenBLAS

- projects.yaml
Closes #156
**Project name**: lazygit
**Project link**: https://github.com/jesseduffield/lazygit
---
> Add project: lazygit

- projects.yaml
Closes #163
**Project name**: Uncrustify
**Project link**: https://github.com/uncrustify/uncrustify
---
> Add project: Uncrustify

- projects.yaml
Closes #166
**Project name**: The Clipboard Project
**Project link**: https://github.com/Slackadays/Clipboard
See #166
---
> Add project: The Clipboard Project

- projects.yaml
Closes #190
**Project name**: Sodium
**Project link**: https://github.com/CaffeineMC/sodium
See #190
---
> Add project: Sodium

- projects.yaml
Closes #194
**Project name**: GoodbyeDPI
**Project link**: https://github.com/ValdikSS/GoodbyeDPI
See #194
---
> Add project: GoodbyeDPI

- projects.yaml
Closes #196
**Project name**: OpenRCT2
**Project link**: https://github.com/OpenRCT2/OpenRCT2
---
> Add project: OpenRCT2

- projects.yaml
Closes #205
**Project name**: Apache Thrift
**Project link**: https://github.com/apache/thrift
---
> Add project: Apache Thrift

- LICENSE
> Update license for better GitHub detection

- projects.yaml
Closes #74
**Project name**: Unmanic
**Project link**: https://github.com/Unmanic/unmanic
---
> Add project: Unmanic

- .github/workflows/validate-test-update.yml
- projects.json
Fixes created in #227 
- Fixed CI trying to push with not changes
> Post #227 fixes

- projects.yaml
Closes #243
**Project name**: typst
**Project link**: https://typst.app/
---
> Add project: typst

- projects.yaml
**Project name**:
**Project link**:
---
> sccache and sccache action

- projects.yaml
**Project name**: BPF Compiler Collection (BCC)
**Project link**: [https://github.com/iovisor/bcc](https://github.com/iovisor/bcc)
---
> Add project: BPF Compiler Collection (BCC)
