mahmoud/zerover

projects.yaml

**Cataclysm: Dark Days Ahead**:
**https://cataclysmdda.org**

Add project. Cataclysm: Dark Days Ahead

---

projects.yaml

Versioning auto-detection is producing the following table entry:
Cataclysm: Dark Days Ahead | 1,775 | 2014 | 15 | 0.9 (2013) | 4.1
-- | -- | -- | -- | -- | --
I expect the following table:
Cataclysm: Dark Days Ahead | 1,775 | 2013 | 15 | 0.C (2015) | 4.1
-- | -- | -- | -- | -- | --
See https://github.com/CleverRaven/Cataclysm-DDA/releases for release versions, in particular
First: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.1
Last: https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.C
(Also fixed a typo)

Correct typos and release auto-detection for Cataclysm: Dark Days Ahead

---

projects.yaml

**Project name**: Pilosa
**Project link**: https://github.com/pilosa/pilosa/
https://www.pilosa.com/blog/

Add project: Pilosa

---

projects.yaml

A longer adherent to zerover than anything listed (22 years since 0.0.7, and still counting - only slrn is older, and it stopped counting four years ago), and over 4000 stars. Its absense is a tragedy.
Note that the GitHub releases are ~80% weird backups; I think there are 55 real ones, but I didn't double check.
Therefore, I included a release count, and hope that overrides gh_url. I also included latest_release, so it can easily be verified if 55 is still accurate; and the rest for consistency, and easier removal of gh_url if it overrides the manual release count.

Add project: ReactOS

---

custom.py

Noticed that sorting wasn't numeric for the Emeriti 0ver Releases table.
Took a stab at fixing it rather than just complaining. Though I be honest, was too lazy to actually test it out. Looks to be roughly equivalent to how stars and releases in the current list work, though.

Sort Emeriti Table

---

projects.yaml

Hi, me again. Turns out Chocolatey follows the principles of 0ver as well!
Addresses #30 
**Project name**: Chocolatey
**Project link**: https://chocolatey.org/

Add project: Chocolatey

---

projects.yaml

**Project name**: Nuitka
**Project link**: https://github.com/Nuitka/Nuitka
**Author**: @kayhayen
2567 stars on GitHub
Initial commit (0.1) in 2010: https://github.com/Nuitka/Nuitka/tree/b301e534507f5a2266f4b37d991cec3ff242ede1
First git tag (0.3.11) in 2011: https://github.com/Nuitka/Nuitka/releases/tag/0.3.11
Latest release (0.6.7) in 2020: https://github.com/Nuitka/Nuitka/releases/tag/0.6.7

Add project: Nuitka

---

projects.yaml

https://inkscape.org/news/2020/05/04/introducing-inkscape-10/

Move Inkscape to alumni (closes #41)

---

projects.yaml

**Project name**: Numba
**Project link**: https://github.com/numba/numba
* 6.5k Github stars
* 35k dependent Github repos
* Widely used in the PyData and scientific computing ecosystems

Add project: Numba

---

projects.yaml

Popular online game, 1.6k stars on Github, 0.x version since 2007
**Project name**: Teeworlds
**Project link**: https://github.com/teeworlds/teeworlds/ / https://teeworlds.com/
Popular online game, available in most Linux distributions
https://en.wikipedia.org/wiki/Teeworlds
---

Add project: Teeworlds

---

projects.yaml

**Project name**: Semgrep
**Project link**: https://github.com/returntocorp/semgrep
- https://r2c.dev/blog/2020/introducing-semgrep-and-r2c/
- https://en.wikipedia.org/wiki/Semgrep
---

Add project: Semgrep

---

projects.yaml

**Project name**: graphile-worker
**Project link**: https://github.com/graphile/worker
- 0.14.0 just released with huge breaking changes.
- 1.3k
- Kind of: Crowd-funded open-source software: https://www.graphile.org/
- Worker queue, so core infra.

Add graphile-worker

---

projects.yaml

**Project name**: Seaborn
**Project link**: https://github.com/mwaskom/seaborn
[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning scheme can obviously be used by everyone, but not every usage is necessarily notable. For Seaborn, the following criteria apply:
Seaborn is a statistical data visualization library in Python that is built on top of Matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics. The wide exposure of Seaborn is evident from its substantial number of GitHub stars and its frequent usage in data analysis and visualization tasks within the Python community.
The notability of Seaborn can be assessed through its GitHub repository and its widespread use in various data science and statistical computing …

projects.yaml: Add Seaborn

---

projects.yaml

**Project name**: Pint
**Project link**:[GitHub](https://github.com/hgrecco/pint) • [PyPi](https://pypi.org/project/Pint)
- Industry standard for unit conversion Python libraries.
- Used by [7.3K GitHub repos](https://github.com/hgrecco/pint/network/dependents).
- Has tag and [82 issues](https://stackoverflow.com/questions/tagged/pint) on StackOverflow.
N/A
---
lmk if you want me to add "Industry standard for unit conversion Python libraries." as the reason.

Add project: pint

---

projects.yaml

Window Maker has been updated between 2017 and 2023 with two additional releases. Updated the projects list to reflect the latest.
https://github.com/window-maker/wmaker/tags
I was surprised to see Window Maker in the list with updates as recent as 2017. Oh, nostalgia. 
When I clicked through, I noticed the more recent releases.

chore: Bump Window Maker from 0.95.8 to 0.96.0

---

projects.yaml

**Project name**: Mihon
**Project link**: https://github.com/mihonapp/mihon
Spiritual succesor of Tachiyomi. As such follows its versioning convention.
N/A

Add project: Mihon

---

projects.yaml

**Project name**: FreeCAD
**Project link**: https://www.freecad.org/
FreeCAD is likely the most mature free software 3D modeling software for CAD (Computer Aided Design) applications. It has been in development since at least 2002, competing with industry giants such as CATIA, Inventor or SolidWorks, who have all long adopted inferior, calendar-based versioning schemes.
Information on the initial release date and version was acquired from https://en.wikipedia.org/wiki/FreeCAD
---

Add project: FreeCAD

---

projects.yaml

The Haskell ecosystem is a gold mine of these, if anyone wanted to farm for them.
**Project name**: transformers
**Project link**: https://hackage.haskell.org/package/transformers
VC link: https://hub.darcs.net/ross/transformers
11444 reverse dependencies on Hackage. The compiler itself depends on it.
Although the first Hackage release is "only" from 2009, the package's history goes back a lot further than that. The repository goes back to 2004, and even then, it wasn't a new project; it was just factored out of another, older project.

Add project: transformers

---

projects.yaml

**Project name**: Tactical RMM
**Project link**: docs.tacticalrmm.com
Used by a bunch of MSP as the only "source available" RMM on the market.
https://docs.tacticalrmm.com/
https://github.com/amidaware/tacticalrmm
---

Add project: Tactical RMM

---

projects.yaml

**Project name**: atlantis
**Project link**: https://github.com/runatlantis/atlantis
Terraform automation tool. Set it up myself in a small startup back in 2019. Few companies later, was talking with coworker regarding Terraform automation and someone mentioned "atlantis". Checked the project again and it still 0ver.

Add project: atlantis

---

projects.yaml

**Project name**: Nushell
**Project link**: <https://www.nushell.sh>
Nushell is an alternative shell that has been around since 2019.
It has a **logo**, dedicated **website**, **32.7k stars** as of Nov 2024 and mature enough to be used as a daily driver.
I'm sending this PR to celebrate its recent [**v0.100.0 release**](https://www.nushell.sh/blog/2024-11-12-nushell_0_100_0.html).

Add Project: Nushell

---

projects.yaml

**Project name**: Fabric API
**Project link**: https://github.com/FabricMC/fabric
Used as the official modding api (for Fabric, not Minecraft) for the Fabric Minecraft mod ecosystem.
---

Add project: Fabric API

---

projects.yaml

Proposing [Thanos project](https://github.com/thanos-io/thanos) (CNCF's Distributed Metric Database) which I co-founded with @fabxc in late 2017 and now smarter people than us continue leading it.
Proudly [v0](https://github.com/thanos-io/thanos/releases/tag/v0.37.0) to support the [ZeroVer's](https://0ver.org/) noble cause.
**Project name**: Thanos
**Project link**: https://github.com/thanos-io/thanos
* https://www.cncf.io/projects/thanos/
* KubeCon EU 2023 talk: https://www.youtube.com/watch?v=2GokLB5_VfY

Add project: Thanos

---

projects.yaml

**Project name**: Discord (for Linux and macOS)
**Project link**:  <https://discord.com/>
[ZeroVer](https://zerover.org)'s patent-pending zero-based versioning scheme can obviously be used by everyone, but not every usage is necessarily notable. Check that the first and at least one other criterion apply:
Discord is a very popular communication platform with 200+ million monthly users. While it is far from open-source and is very commercial; it does allow custom bots to interact quite in-depth with the platform through a well-documented API. It is quite customizable in terms of creating communities and has excellent moderation tools. However, Discord does not support any level of self-hosting, federation, or even built-in end-to-end encryption. All information sent on the platform is …

Add project: Discord for Linux and macOS. Ref #191

---

projects.yaml

Closes #124
**Project name**: libc
**Project link**: https://github.com/rust-lang/libchk
See #124
---

Add project: libc (Rust)

---

projects.yaml

Closes #202
**Project name**: TypeORM
**Project link**: https://github.com/typeorm/typeorm
---

Add project: TypeORM

---

projects.yaml

Yesterday I accidentally made duplicate projects for OpenRCT2 and GoodbyeDPI because their issues were still open. This PR removes the duplicates I added.

Remove duplicate projects

---

projects.yaml

Moved `esbuild` and `yup` to the GitHub projects section.

Clean up project.yaml a little bit

---

projects.yaml

Closes #241
[n8n's tags](https://github.com/n8n-io/n8n/tags) can't be scanned automatically due to the prefix (#237 would fix). For now I hardcoded the release information.
This prompted a couple questions:
- Should n8n even be in this list? It was 0ver for 4 years (2019-2023), and it was only added to the list [3 days ago](https://github.com/mahmoud/zerover/pull/229).
- Do you consider the last 0ver release the newest 0ver release or the one preceding the first non-0ver release? Because lot's of times I see repos publishing many 0ver releases past their first non-0ver release (for fixes/patches and such).

Fix project: n8n

---

projects.yaml

Prosody left 0ver status today with the [announcement of Prosody 13.0.0](https://blog.prosody.im/prosody-13.0.0-released/).
The Prosody repo was never on Github, and this was linking to a third-party mirror of the repository. Now that the 0ver-related project metadata is not really going to change anyway, I've switched it to point to the official repo and manually entered all the relevant keys into projects.yaml.
The data for the keys can be verified at https://prosody.im/doc/release/ and https://hg.prosody.im/trunk/tags
Farewell 0ver, it was fun while it lasted, but alas, all good things must come to an end! :'(

Move Prosody to emeritus status, update metadata

---

tools/gen_projects_json.py

`README.md` indicates that `latest_release_version` should be set for ZeroVer projects that aren't from GitHub or that have an unusual tagging system.  However, a number of projects in that situation were being incorrectly listed as emeritus:
ASCEND
Cataclysm: Dark Days Ahead
Compiz
Dash
Discord for Linux
Discord for OSX
JED
MAME
OpenStreetMap API/website
PuTTY
Tiny C Compiler
XeTeX
distlib
docutils
gettext
three.js
transformers

Fix more manual entries to be 0ver
